[tool.poetry]
name = "fizzbuzz_1.0"
version = "0.1.0"
description = ""
authors = ["Pablo Fernandez <fernandezpablo85@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
